# Generated by Django 5.0.2 on 2024-02-07 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.ForeignKey(
                max_length=30,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.post",
                verbose_name="제목",
            ),
        ),
    ]
