# Generated by Django 5.0.2 on 2024-02-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30, verbose_name="제목"),
        ),
    ]
