# Generated by Django 5.0.1 on 2024-02-05 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_relationship"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                related_name="followers",
                through="users.Relationship",
                to=settings.AUTH_USER_MODEL,
                verbose_name="팔로우 중인 사용자들",
            ),
        ),
    ]
